config/routes.rb
Dms4u32::Application.routes.draw do
  
  root :to => 'dashboard#index'

  post "sign_in" => "authentication#login"

  get "sign_in" => "authentication#sign_in"

  post "new_user" => "authentication#register"

  get "account_settings" => "authentication#account_settings"

  post "account_settings" => "authentication#set_account_info"

  get "forgot_password" => "authentication#forgot_password"

  put "forgot_password" => "authentication#send_password_reset_instructions"

  get "password_reset" => "authentication#password_reset"

  put "password_reset" => "authentication#new_password"

  match 'sign_in' => 'authentication#sign_in'

  match 'sign_out' => 'authentication#sign_out'

  match 'change_password' => 'authentication#change_password'
  
  match 'new_user' => 'authentication#new_user'

  match 'forgot_password' => 'authentication#forgot_password'

  match 'password_sent' => 'authentication#password_sent'

  match ':controller(/:action)(.:format)' => 'controller#action'

end

app/views/layouts/admin.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang='en'>
<head>
	<meta httpd-equiv='Content-Type' content='text/html; charset=utf-8'>
	<title>DMS4U | <%= @page_title || 'Public Area' %></title>
	<meta name='author' content='XiangJun Wang'>
	<%= stylesheet_link_tag('application', :media => 'all') %>
	<%= javascript_include_tag('application', :media => 'all') %>
</head>
<body>
	<div class='navbar navbar-default navbar-fixed-top' role='navigation'>
		<div class='container'>
			<% if current_user %>
				<ul class='nav nav-tabs'>
					<li <% if @nav_id == 'nav-dashboard' %> 
							<%= "class='active'" %>
						<% end %>
					 	>
					 	<%= link_to 'Dashboard', :controller => 'dashboard' %>
					</li>
					<% unless current_user.role.nil? %>
						<% if current_user.role.name == 'Administrator' %>
							<li <% if @nav_id == 'nav-users' %>
									<%= "class='active'" %>
								<% end %>
								>
								<%= link_to 'Users', :controller => 'users', :action => 'list' %>
							</li>
							<li <% if @nav_id == 'nav-settings' %>
								<%= "class='active'" %>
							<% end %>
							>
							<%= link_to 'Settings', :controller => 'settings', :action => 'unit' %>
						</li>
						<% end %>
					<% else%>
						<% flash[:warning] = 'You should create role in database. Please contact administrator.' %>
					<% end %>
					<li <% if @nav_id == 'nav-accounts' %>
							<%= "class='active'" %>
						<% end %>
						>
						<%= link_to 'Accounts', :controller => 'accounts', :action => 'list' %>
					</li>
					<li <% if @nav_id == 'nav-transactions' %>
							<%= "class='active'" %>
						<% end %>
						>
						<%= link_to 'Transactions', :controller => 'transactions', :action => 'list' %>
					</li>
					<li <% if @nav_id == 'nav-blogs' %>
							<%= "class='active'" %>
						<% end %>
						>
						<%= link_to 'Blogs', :controller => 'blogs', :action => 'list' %>
					</li>
				</ul>
				<div class="btn-group">
					<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
						Logged in as <%= current_user.username %> <span class="caret"></span>
					</button>
					<ul class="dropdown-menu" role="menu">
						<li><%= link_to current_user.username, account_settings_path %></li>
						<li class="divider"></li>
						<li><%= link_to "Sign Out", sign_out_path %></li>
					</ul>
				</div>
			<% else %>
				<div id='navigator'>
					<%= link_to "Sign up", new_user_path, class: 'navbar-link' %>&nbsp;&nbsp;&nbsp;
					<%= link_to "Sign In", sign_in_path, class: 'navbar-link' %>
				</div>
			<% end %>
		</div>
	</div>
	<div class='container'>
		<% flash.each do |name, msg| %>
			<% if name.to_s == 'notice' %>
				<%= content_tag :div, msg, :id => "flash_#{name}", :class => 'alert alert-success' %>
			<% elsif name.to_s == 'warning' %>
				<%= content_tag :div, msg, :id => "flash_#{name}", :class => 'alert alert-warning' %>
			<% elsif name.to_s == 'info' %>
				<%= content_tag :div, msg, :id => "flash_#{name}", :class => 'alert alert-info' %>
			<% elsif name.to_s == 'error' %>
				<%= content_tag :div, msg, :id => "flash_#{name}", :class => 'alert alert-danger' %>
			<% end %>
		<% end %>

		<div id='content'>
			<%= yield %>
		</div>
		<div class='clear'></div>
	</div>
	<div id='footer'>
		<div class='container'>
			<p id='copyright'>&copy; Copyright 2014 </p>
		</div>
	</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dms4u32</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang='en'>
<head>
	<meta httpd-equiv='Content-Type' content='text/html; charset=utf-8'>
	<title>DMS4U | <%= @page_title || 'Public Area' %></title>
	<meta name='author' content='XiangJun Wang'>
	<%= stylesheet_link_tag('application', :media => 'all') %>
	<%= javascript_include_tag('application', :media => 'all') %>
</head>
<body>
	<div class='container'>
		<div id='main'>
			<div id='navigation'>
				<p>
					<% if current_user %>
						Logged in as <%= current_user.username %>.
						<%= link_to "Sign Out", sign_out_path %>
						 <%= link_to "Account Settings", account_settings_path %>
					<% else %>
						<%= link_to "Sign up", new_user_path %> or
						<%= link_to "Sign In", sign_in_path %>
					<% end %>
				</p>
			</div>
			<% flash.each do |name, msg| %>
			<%= content_tag :div, msg, :id => "flash_#{name}" %>
			<% end %>

			<div id='content'>
				<%= yield %>
			</div>
			<div class='clear'></div>
		</div>

		<div id='footer'>
			<p id='copyright'>&copy; Copyright 2014 </p>
		</div>
	</div>
</body>
</html>